#include <string>
#include <iostream>
void initial(char[],char[],char[]);
int lenght_check(std::string);
int En_check(char*);
int symbol_check(char*);
int number_check(char*);
int num_word(char*);
std::string num_sym_word(char*);